### ISSUE TITLE
Metadata information not found (problem_list.csv)

### ISSUE THREAD

**Issue by states786** [IBM/Project_CodeNet#17]
Hi, 

I am in search of description file, which can describe a brief summary depicting the implementation details of each set of problem in Project_CodeNet_Java250 dataset. 

Right now, dataset is available without any description of meta data. I tried to find a file named as "problem_list.csv", but in vain. Can you please share this information?

**Comment by geert56** [comment]
The additional benchmark datasets like Project_CodeNet_Java250 are pure data (and not metadata) extracts from the larger Project_CodeNet dataset. The former will use the same problem ids and submissions ids as the latter.
However, Project_CodeNet comes with all the metadata. So you will find the file "problem_list.csv" there and also all the individual "metadata/p?????.csv" files.

It would be a good idea if the complete metadata would be available as a separately downloadable archive.
We will be working on that.

**Comment by states786** [comment]
Thanks for your response. 

Will it be convenient for you to share metadata file and any other associated file for "Project_CodeNet_Java250" dataset? 
I check the size of the complete dataset, which is around 7.8 GB, quite large.

**Comment by geert56** [comment]
We are in the process of sharing all metadata as a separate archive on DAX. That file would be some
291 MB, so much smaller than the full dataset at 7.8 GB. With that metadata you would be able to (back)reference the submissions found in e.g. Project_CodeNet_Java250 (and all other derived benchmark datasets). The relationship among data and metadata is spelled out here: https://github.com/ibm/project_codenet#relationships-among-the-metadata-and-data.

**Comment by geert56** [comment]
All metadata is now separately available as a downloadable tar archive here:
https://dax-cdn.cdn.appdomain.cloud/dax-project-codenet/1.0.0/Project_CodeNet_metadata.tar.gz?_ga=2.95870620.1494682072.1622480730-463534291.1622235075.

With this, I close this issue.

**Comment by Viktour19** [comment]
Can you kindly update the Readme with this separate metadata link?
Also the following files are empty

`.p02015.csv`
`.p02395.csv`
`p02387.csv`
`p02478.csv`
`p02533.csv`

**Comment by geert56** [comment]
Yes, we will update the README with a link to the separate metadata.
Your observation of the "empty" metadata for these 5 problems is correct. Those problems have no
submissions under the "data" folder. For reasons of consistent "problem" numbering the empty .csv files and empty data directories are kept for them, rather then removing the files and directories. I believe this is mentioned somewhere. I hope this answer is satisfactory and will let me close this issue.
