### ISSUE TITLE
Backdoor detected

### ISSUE THREAD

**Issue by benreaves** [IBM/Project_CodeNet#18]
Apologies if this has already been reported, but Windows Security is detecting a backdoor threat Backdoor.PHP/Dirtelti.MTF in 4 php files in the download from this repository

> BackdoorPHP/Dirtelti.MTF
> Alert level: Severe
> Status: Active
> Date: 2021-06-05 10:58
> Category: Backdoor
> Details: This program provides remote access to the computer it is
> installed on.
> Learn more
> Affected items:
> containerfile: C:\Users\b\DownIoads\Project_CodeNettar.gz
> containerfile: C:\Windows\Temp\TMPDB22CA7DF94B81B2
> file: C:\Users\b\DownIoads\Project_CodeNet.tar.gz->(GZip)->Project_CodeNet/data/p03844/PHP/s069566612.php
> file: C:\Users\b\DownIoads\Project_CodeNet.tar.gz->(GZip)->Project_CodeNet/data/p03844/PHP/s308064656.php
> file: C:\Users\b\DownIoads\Project_CodeNet.tar.gz->(GZip)->Project_CodeNet/data/p03844/PHP/s6862216O0.php
> file: C:\Users\b\DownIoads\Project_CodeNet.tar.gz->(GZip)->Project_CodeNet/data/p03844/PHP/s967662473.php

**Comment by geert56** [comment]
All these 4 PHP files contain "eval(gets(STDIN))", i.e., they read anything from standard input and evaluate it without any check whether the input is benign or malicious. Note however that we supply these files as data; we do not assume that users will run these files. Only then would they cause a threat.

**Comment by benreaves** [comment]
I see. Thank you. You may hear others concerns because Microsoft does classify these as a threat. But now I understand I'll close this

**Comment by benreaves** [comment]
One more footnote: I was particularly suspicious because it was found in the zipped file in the Downloads folder, and I was unable to delete it using Windows File Explorer, nor with ubuntu running under WSL1
I suppose it's the same issue as described at https://windows.php.net
(I was able to delete it using Windows Safe Mode, but now I see it wasn't really a threat so I can ignore it)

Thank you

**Comment by geert56** [comment]
Thank you for doing a meticulous check on our dataset. I am surprised since we only keep links to the DAX dataset here on the github. Again, the files you listed are collected by us and originate from an online judging site that accepts user submissions to programming problems. It can therefore not be avoided that some submissions might contain backdoors and in general vulnerable code. We have decided not to filter these files. We are considering perhaps putting up a disclaimer to this effect on the dataset site.

**Comment by geert56** [comment]
By the way, not being able to "delete" the files on Windows (and Ubuntu) may be caused by the fact that the gzipped tar file contains Linux read-only files, i.e., the original Linux file permissions are set to octal 444.
