### ISSUE TITLE
Please share SPT split (into 8 CSVs) mechanism for problem class ID 0 and 1 for GNN experiment. 

### ISSUE THREAD

**Issue by singlelionwith2cubs** [IBM/Project_CodeNet#23]
Please share SPT split (into 8 CSVs) mechanism used in gnn experiment for problem class ID 0 and 1.

**Comment by vthost** [comment]
Thank you for your interest in our experiments!

Please note that the GNNs do not represent our work, the experiments are intended to showcase example uses of our datasets. We lack the resources to provide extended support for custom data.
