### ISSUE TITLE
Please share what's the best possible mechanism to build a deployable pipeline for gnn model based code classification

### ISSUE THREAD

**Issue by singlelionwith2cubs** [IBM/Project_CodeNet#24]
Please share what's the best possible mechanism to build a deployable pipeline for gnn model based code classification

**Comment by vthost** [comment]
Please note that the GNN experiments are intended to showcase example uses for our datasets. For further support, we suggest to look at the popular frameworks DLG and Pytorch Geometric, or benchmarks such as the Open Graph Benchmark.
