### ISSUE TITLE
Feature extraction for GNN example

### ISSUE THREAD

**Issue by EricYizhenWang** [IBM/Project_CodeNet#32]
Hi,

Thanks for release the dataset with baseline methods. I have a question regarding the GNN example in https://github.com/IBM/Project_CodeNet/tree/main/model-experiments/gnn-based-experiments . The data is preprocessed into the form of .csv files. May I know how I can obtain these files from the original c++1000 dataset? I'm asking partly because there seems to some additional treatment such as the next node token on top of the SPT representation, so it would be great to have a step by step tutorial of obtaining the processed data in the first place.

I'm working on a project using the dataset, so your timely reply will be invaluable. Thanks in advance.

**Comment by EricYizhenWang** [comment]
Thanks for the quick response! I'm able to run over the full dataset in SPT form. My question is whether I can generate the SPT files from the source code myself. Are the .csv files generated using the SPT generate in the repo?

**Comment by vthost** [comment]
We do not provide the scripts but the csv files should be easy to generate if you have your own data (e.g., an AST or similar). Here is a description of what you need to write out:
https://github.com/IBM/Project_CodeNet/issues/22#issuecomment-866035171
