### ISSUE TITLE
Didn't find any wrong solutions in Project_CodeNet_Python800 dataset

### ISSUE THREAD

**Issue by SlinkoIgor** [IBM/Project_CodeNet#35]
Project_CodeNet_Python800 and Project_CodeNet_Java250 consist of Accepted answers only. Wonder, where do I find the Wrong solutions?

**Comment by geert56** [comment]
Correct. There are no "wrong" solutions in the benchmark datasets that you mentioned.
Those derived datasets were particularly curated to only consist of Accepted solutions such that they
correctly compile and run. If you would like some of the "wrong" submissions to the problems mentioned
in the benchmark datasets you will have to download the full Project CodeNet dataset. Instructions are of course in the README for this github.
