### ISSUE TITLE
Script for testing Input-Output

### ISSUE THREAD

**Issue by karths8** [IBM/Project_CodeNet#37]
In the README file for the input-output data in CodeNet the authors say - "For every problem, input was fed into accepted solution programs in order to check if the output from the solution program matched the output file". Would it be possible for the authors to share the script they used to automate the above process? 

Also, another question I had was regarding the "verified" tag given to problems. The README file associated with the input-output data says - 

"We considered problem input and output to be "verified" if program output matched the output file for at least one tested program in any of the four programming languages used. As mentioned, there may be differences in formatting of solutions. Thus, "verified" problem input will not always produce output that is identical to the output file in accepted programs." 

My question here is, what then is the purpose of the "verified" tag if it does not ensure that the produced output matches the specifications given in the output file?

Any help regarding these issues will be greatly appreciated. Thanks in advance!

**Comment by lindseydecker** [comment]
We would be happy to share the script that you requested and will add it to this github repo as soon as possible. We’ll let you know when it becomes available.

The purpose of the “verified” tag is that it confirms that the input and output scraped from the problem description HTML file are correct. When an accepted solution program for a “verified” problem is fed the input, the output that is produced should meet the required specifications written in the problem description HTML file, although it may not exactly match our output file. While not all accepted solution programs will produce exactly the same output, we would expect them only to vary in terms of formatting.

Different problems may have different requirements as well as strictness for the formatting of the output (e.g. one problem may require output to have three decimal places while another may accept output with any number of decimal places). When determining “verified” programs, we simply looked for output that exactly matched our output files. Therefore, for the “verified” problems, we found that there exists at least one accepted solution program that when fed the input will exactly produce the output in the corresponding output file. It is certainly possible that input and output for “unverified” problems are also correct.  

Please let us know if you have anymore questions. Thanks for your interest!
