### ISSUE TITLE
Would Loyc trees be useful for ML-based language translation and prediction?

### ISSUE THREAD

**Issue by qwertie** [IBM/Project_CodeNet#4]
I'm not a machine learning expert by any means. However, I think that there may be some value in running multi-language ML models against an intermediate language rather than against the original source text. For example, the following two statements are essentially identical in meaning, but not in form:

~~~cs
if (x > 0 && x <= y) {
  process(x, y);
} else {
  addError("Out of range");
}
~~~

~~~py
if x > 0 and x <= y:
  process(x, y);
else:
  addError("Out of range");
~~~

For some years I've been developing an interchange format for code, which would map these two blocks to an identical intermediate form. While ML models can presumably learn all by themselves that these two blocks are "the same", I suspect it would be beneficial to "help" models understand common similarities in a more explicit way.

By analogy, 7-zip can compress a file down to a lower size when the original file is already expressed more efficiently (e.g. given an xml file and a binary file representing the same data, the size of the compressed binary file is smaller, even if the compression ratio isn't as good). Similarly, I speculate that adjusting different languages to be more similar to each other in a preprocessing step would spare the model from having to deal with irrelevant syntactic differences, allowing it to dedicate more resources to the (still very numerous) remaining differences.

Since I only work on this in my free time (and I have several other free-time projects), important parts of a [Loyc tree](http://loyc.net/loyc-trees/) standard are un/underdeveloped. Even so I would like to hear from ML researchers about whether something like this could be a useful tool for them.

**Comment by geert56** [comment]
Thanks for your extensive suggestions. I agree that AI models should not be deployed to simply learn a language syntax. Those are explicit in the form of grammars. Having some common internal format is always a good approach. Some researchers are e.g. using the internal code representation (IR) as defined by LLVM for that purpose. I assume that Loyc trees can play a similar role. Tree sitter of course provides a convenient framework for parser generation and program analysis. But I suspect that program translation sets goals that go beyond a mere syntactic constructs mapping; not just the semantics must be preserved but preferably the outcome is a better program in some sense, e.g. by adhering to the target language idiom and maybe have better performance than the original program. We see that with Cobol to Java translation where customers insist on deriving a result that is not just Cobol disguised in Java syntax. Anyway, it's a hard problem and will quite come effort and time to solve.

**Comment by mihirc36** [comment]
To answer your question from an AI/ML perspective, quite a bit of pre-processing is done on raw source code to "normalize" user-specific names and program specific tokens, before being consumed by an AI/ML model for training/inference. However, most, if not all, AI/ML flows out there today perform pre-processing in a language-specific manner, rather than in ways that can be used across several languages. The simplified parse tree generator that is available as part of Project CodeNet is a step towards have a multi-language approach to applying ML/AI models.

**Comment by geert56** [comment]
Since this thread has been dormant for a while, I take the liberty to close the issue for now.
