### ISSUE TITLE
approximate gpu memory usage when training

### ISSUE THREAD

**Issue by jihyechoi77** [IBM/Project_CodeNet#44]
Hello, thank you for your awesome work on large-scale source code dataset!

I am training CNN and GNN models for code classification task by following the instructions on section 8.1 of paper, and under directory model-experiments/.
As the dataset is pretty large-scale (e.g. with C++ codes with token sequence, I obtained 4293714 code solutions for 2471 problems, with longest code has 200520 tokens), I'd like to check with you what was the approximate memory usage of GPUs when training the models. 

Also, would it be possible to get the implementation of C-BERT as well?

Thank you in advance!

**Comment by weidotwisc** [comment]
Hi, 

All our experiments were conducted on 16 GB GPUs. Hope it helps! 

Thanks! 

Wei
