### ISSUE TITLE
What is type-4 similarity?

### ISSUE THREAD

**Issue by vadim0x60** [IBM/Project_CodeNet#49]
A sentence from README. "The problem-submission relationship in Project CodeNet corresponds to type-4 similarity and can be used for code search and clone detection". Some readers (me included) do not know what this refers to. Turning "type-4 similarity" into a hyperlink to a page that explains the concept would be very useful.

**Comment by project-codenet** [comment]
Hi Vadim, a link has been added to explain type-4 similarity. The README should be updated by Monday. The link is to this PhD thesis https://escholarship.org/uc/item/45r2308g. You can find the definition on page 6.
