### ISSUE TITLE
Artifacts for Project CodeNet paper are not available.

### ISSUE THREAD

**Issue by nashid** [IBM/Project_CodeNet#5]
The initiative of having an authoritative dataset is valuable. It could serve as a benchmark for different source code processing tasks like code summarization or language to language translation.

For the CodeNet paper, results are reported for code classification and code similarity experiments. However, the models and configuration scripts for MLP, CNN, or GNN are not available, and artifacts are not made available for replication.

I would like to know whether there is a plan to share the replication package for the CodeNet paper. I would be happy to get involved if there is any assistance required to make the replication package ready.

**Comment by project-codenet** [comment]
Link to paper is fixed now, thanks for the heads up

**Comment by project-codenet** [comment]
Sorry, Nashid. I misunderstood your comment. We have just added a package in directory model-experiments. We plan to add more very soon.

**Comment by nashid** [comment]
@project-codenet thanks for sharing the artifacts for the MLM model. 
We would be interested to know when are you planning to share the GNN models particularly?

**Comment by project-codenet** [comment]
@nashid we just added a package on code similarity and classification using tokens based techniques.
We will add a package on GNN models next week. 
Thanks for your interest and feedback

**Comment by vthost** [comment]
We need a little more time, but will add them next week. Thank you for your interest!

**Comment by nashid** [comment]
@vthost great, thank you.

**Comment by vthost** [comment]
I close this issue given that we uploaded the files. See [here](https://github.com/IBM/Project_CodeNet/tree/main/model-experiments/gnn-based-experiments).
