### ISSUE TITLE
Please consider putting the problem descriptions in the "MiniCodeNet" dataset

### ISSUE THREAD

**Issue by geajack** [IBM/Project_CodeNet#51]
The MiniCodeNet dataset was a good idea for people on slow connections, but I was disappointed to find it doesn't contain the problem descriptions, since those were really the only parts I cared about. Alternatively, maybe add a download with just the problem descriptions/metadata to the downloads page.

Thanks!

**Comment by ufinkler** [comment]
Added all the problem descriptions to the 'doc' directory as a compressed tar archive for direct download.
