### ISSUE TITLE
Dataset Split for Benchmark Code Classification

### ISSUE THREAD

**Issue by xieexiaotuzi** [IBM/Project_CodeNet#53]
Hi,
Thanks for sharing such a great AI code dataset.

In Page 8 Section 8.1 of the paper, there  shows  " For each experiment, 20% of the code samples are used for testing, while the rest are split in 4:1 for training and validation, respectively". However, in page 12 "GNN with SPT", there shows "We conduct 6/2/2 random split for each of the 4 benchmarks: i.e., 60% training data, 20% testing data, and 20% validation data."

I am confused about the differences. Could you please help me with this?

Best,
    LJ.

**Comment by weidotwisc** [comment]
Hi, 

Thank you very much for your interest in our paper! 

We made a typo in "For each experiment, 20% of the code samples are used for testing, while the rest are split in 4:1 for training and validation, respectively" --  It should have been *3*:1. The description of the GNN experiments remains intact. 

Thanks! 

Wei

**Comment by xieexiaotuzi** [comment]
Thanks for your reply. Could you please help me where could I find the split. 
Thanks.
